[project]
name = "repl-nix-studentmanagementsystem"
version = "0.1.0"
description = "Add your description here"
requires-python = ">=3.11"
dependencies = [
    "flask-login>=0.6.3",
    "flask-sqlalchemy>=3.1.1",
    "flask>=3.1.0",
    "werkzeug>=3.1.3",
]
